### ISSUE TITLE
講習会の予定を追加する

### ISSUE THREAD

**Issue by miyaji255** [OUCC/oucc.github.io#10]
|日付|内容|担当|時間|備考|
|-|-|-|-|-|
|4/15(土)|python|YuraYura|18:00 ~|pythonの基礎を学びます。|
|4/16(日)|C|NamiFuji|14:00~|C言語の基礎を学びます。|
|4/20(木)|C++|めとべる|19:00~|C++の基礎を学びます。|
|4/22(土)|Flutter|MrMocchy|14:00~|Flutterを用いてアプリ制作について学びます。|
|4/23(日)|Blender|しーちきん,ゴリラ|14:00~|Blenderを用いて3Dモデリングについて学びます。|
|5/ 4(木)|競プロ|外部(KowerKoint)|14:00~|競技プログラミングについて学びます。|
|5/ 6(土)|C#|SIOTHK しお|14:00~|C#の基礎を学びます。|
|5/ 7(日)|Unity|kaeru|14:00~|Unityを用いてゲーム制作を学びます|
|5/11(木)|Linux|紅茶|19:00~|Linux（サーバや組み込み用途で広く利用されている OS）について学びます。|
|5/13(土)|AI|ヘリン,亮太|14:00~|AIについて学びます|
|5/14(日)|AI|ヘリン,亮太|14:00~|5/13(土)の講習会に続いて、AIについて学びます。|
|5/18(木)|HTML/CSS/javascript|yuyu|19:00~|HTML/CSS/javascriptを用いたWebサービスの制作について学びます。|
|5/20(土)|Git|みやじ|14:00~|Git(ソースコードの編集履歴を管理するシステムで、複数人での開発等にも使われています)の基礎を学びます。|
|5/21(日)|React|Ciffelia|14:00~|Reactを用いてWebサービス制作について学びます。|

**Comment by ciffelia** [comment]
https://oucc.org/workshop/
